### ISSUE TITLE
on windows 8 + mrpt 1.3.0: webcams don't work in camera-calib.exe

### ISSUE THREAD

**Issue by gitunit** [jlblancoc/mrpt#129] opened 2015-01-23 18:58 UTC
i've tried two webcams, one notebook built-in cam and one usb-cam.
these cameras don't work with the new version.
however, both cameras work flawlessly with version mrpt 1.2.2

**Comment by jlblancoc** [comment] 2015-01-23 21:08
My guess is that you refer to the precompiled (Windows installer) mrpt version, right? 
In that case, the problem is *probably* related to mrpt shipping opencv 3.0.0 beta instead of the previous 2.8.x. 

The best way to find out more is if you try to build mrpt from sources against opencv 2.8.x and check again...

**Comment by gitunit** [comment] 2015-01-24 12:59
yes, its the precomiled version. i will see if i can recompile it with another opencv version. i have 2.4.9 on my machine, will that work with mrpt?

**Comment by jlblancoc** [comment] 2015-01-24 13:06
Sure

**Comment by jlblancoc** [comment] 2015-02-15 19:43
Will close this, unless it's confirmed that the problem is mrpt-specific.

**Closed by jlblancoc** 2015-02-15 19:43 UTC
